# Generated by Django 6.0.6 on 2026-06-15 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='category_icons/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ServicePackage Categories',
                'db_table': 'service_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('booking_type', models.CharField(choices=[('instant', 'Instant Booking'), ('scheduled', 'Scheduled Booking'), ('both', 'Both')], default='both', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_duration_mins', models.IntegerField(default=60)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.service')),
            ],
            options={
                'db_table': 'service_pricing',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('images', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.serviceprovider')),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(fields=['provider', 'rating'], name='reviews_provide_e960ec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='services_categor_6a9f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['service', 'city', 'is_active'], name='service_pri_service_b8e802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricing',
            unique_together={('service', 'city')},
        ),
    ]
