web: gunicorn visvasahome.wsgi --workers 4 --bind 0.0.0.0:$PORT --timeout 120
worker: celery -A visvasahome worker -l info --concurrency 4
beat: celery -A visvasahome beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
